version: "3.5"
services:
  xpgg_web:
    image: xiaopgg/xpgg_web:3000
    container_name: xpgg_web
    stop_signal: SIGINT
    restart: always
    ports:
      # 自动化平台nginx端口号
      - "80:80"
      # admin后台nginx端口号
      - "8000:8000"
      # django的启动端口号
      - "8005:8005"
      # rsync同步端口
      - "873:873"
    volumes:
      # 挂载外部目录，用于迁移使用
      - "./files/xpgg:/data/www/xpgg"
      - "./files/xpgg_pro:/data/www/xpgg_pro"
      - "./files/xpgg_co:/data/xpgg_co"
      - "./files/salt/pki/minion:/etc/salt/pki/minion"
      - "./files/nginx/vhosts:/usr/local/nginx/conf/vhosts"
      # 时区以宿主机为准
      - "/etc/localtime:/etc/localtime:ro"
    env_file: .env
    depends_on:
      - redis
      - mysql
    networks:
      xpgg_net:
        ipv4_address: 172.18.18.10
  redis:
    image: redis:4.0
    container_name: xpgg_redis
    stop_signal: SIGINT
    restart: always
    volumes:
      # 挂载外部目录，用于迁移使用
      - "./files/redis:/data"
      - "/etc/localtime:/etc/localtime:ro"
    env_file: .env
    expose:
       - "6379"
    command: redis-server --appendonly yes --requirepass '${REDIS_PASSWORD}'
    networks:
      xpgg_net:
        ipv4_address: 172.18.18.20
  mysql:
    image: mysql:5.7
    container_name: xpgg_mysql
    stop_signal: SIGINT
    restart: always
    volumes:
      # 挂载外部目录，用于迁移使用
      - "./files/mysql/conf/my.cnf:/etc/my.cnf"
      - "./files/mysql/data:/var/lib/mysql"
      - "./files/mysql/init_data:/docker-entrypoint-initdb.d"
      - "/etc/localtime:/etc/localtime:ro"
    env_file: .env
    expose:
       - "3306"
    networks:
      xpgg_net:
        ipv4_address: 172.18.18.30
networks:
  xpgg_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.18.0/24"
